branch-defaults:
  master:
    environment: test3app
environment-defaults:
  test3app:
    branch: null
    repository: null
global:
  application_name: test3app
  default_ec2_keyname: laravel-test
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/PHP 7.1 running
    on 64bit Amazon Linux/2.6.6
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
